name: Build and Dev Check

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-dev-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 10
          run_install: true
          cache-dependency-path: pnpm-lock.yaml

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      # - name: Install dependencies
      #   run: pnpm install --frozen-lockfile

      - name: Check dev command
        run: |
          # 只检查编译是否成功，不需要启动服务器
          pnpm run compile && echo "Dev compilation successful"

      - name: Check build command
        run: pnpm run build

      - name: Lint check
        run: pnpm run lint