name: Build and Dev Check

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-dev-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Check dev command
        run: |
          # 只检查编译是否成功，不需要启动服务器
          yarn compile && echo "Dev compilation successful"

      - name: Check build command
        run: yarn build

      - name: Lint check
        run: yarn lint